/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type NavLink = {
  _type: "navLink";
  label?: string;
  route?: "/" | "/products" | "/products/search" | "/favorites" | "/cart";
};

export type ExternalLink = {
  _type: "externalLink";
  label?: string;
  url?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ProductCarouselModule = {
  _type: "productCarouselModule";
  title?: string;
  description?: string;
  category?: string;
  limit?: number;
};

export type HeroModule = {
  _type: "heroModule";
  heading?: string;
  subheading?: string;
  cta?: NavLink;
};

export type Modules = Array<
  | ({
      _key: string;
    } & HeroModule)
  | ({
      _key: string;
    } & ProductCarouselModule)
>;

export type RouteMeta = {
  _id: string;
  _type: "routeMeta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  route?: "/products" | "/products/search" | "/favorites" | "/cart" | "/404";
  title?: string;
  description?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: BlockContent;
  modules?: Modules;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerContact?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  footerStack?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  copyrightHolder?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | NavLink
  | ExternalLink
  | BlockContent
  | ProductCarouselModule
  | HeroModule
  | Modules
  | RouteMeta
  | Page
  | Slug
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    copyrightHolder,    headerNav[]{ _key, label, route },    footerContact[]{ _key, label, url },    footerStack[]{ _key, label, url }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      copyrightHolder: null;
      headerNav: null;
      footerContact: null;
      footerStack: null;
    }
  | {
      copyrightHolder: string | null;
      headerNav: Array<{
        _key: string;
        label: string | null;
        route:
          | "/"
          | "/cart"
          | "/favorites"
          | "/products"
          | "/products/search"
          | null;
      }> | null;
      footerContact: Array<{
        _key: string;
        label: string | null;
        url: string | null;
      }> | null;
      footerStack: Array<{
        _key: string;
        label: string | null;
        url: string | null;
      }> | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    description,    body,    modules[]{      _key,      _type,      _type == "heroModule" => {        heading,        subheading,        cta{ label, route }      },      _type == "productCarouselModule" => {        title,        description,        category,        limit      }    }  }
export type PAGE_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  body: BlockContent | null;
  modules: Array<
    | {
        _key: string;
        _type: "heroModule";
        heading: string | null;
        subheading: string | null;
        cta: {
          label: string | null;
          route:
            | "/"
            | "/cart"
            | "/favorites"
            | "/products"
            | "/products/search"
            | null;
        } | null;
      }
    | {
        _key: string;
        _type: "productCarouselModule";
        title: string | null;
        description: string | null;
        category: string | null;
        limit: number | null;
      }
  > | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: ROUTE_META_QUERY
// Query: *[_type == "routeMeta" && route == $route][0]{    title,    description  }
export type ROUTE_META_QUERY_RESULT = {
  title: string | null;
  description: string | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current) && slug.current != "home"].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    copyrightHolder,\n    headerNav[]{ _key, label, route },\n    footerContact[]{ _key, label, url },\n    footerStack[]{ _key, label, url }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title,\n    description,\n    body,\n    modules[]{\n      _key,\n      _type,\n      _type == "heroModule" => {\n        heading,\n        subheading,\n        cta{ label, route }\n      },\n      _type == "productCarouselModule" => {\n        title,\n        description,\n        category,\n        limit\n      }\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "routeMeta" && route == $route][0]{\n    title,\n    description\n  }\n': ROUTE_META_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current) && slug.current != "home"].slug.current\n': PAGE_SLUGS_QUERY_RESULT;
  }
}
