packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 4320

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true

catalog:
  "@biomejs/biome": "^2.5.6"
  "@types/node": "^24.13.3"
  "@types/react": "19.2.18"
  "@types/react-dom": "19.2.4"
  babel-plugin-react-compiler: "^1.0.0"
  clsx: "^2.1.1"
  next: "16.3.0"
  react: "^19.2.8"
  react-dom: "^19.2.8"
  turbo: "^2.10.8"
  typescript: "7.0.2"
  next-intl: "^4.13.4"
  usehooks-ts: "^3.1.1"
  ky: "^2.0.2"
  "@tanstack/react-query": "^5.101.4"
  "@storybook/nextjs-vite": "^10.5.6"
  "@storybook/react": "^10.5.6"
  lucide-react: "^1.28.0"
  open-props: "^1.7.23"
  schema-dts: "^2.0.0"
  nuqs: "^2.9.4"
  "@tanstack/react-form": "^1.33.3"
  storybook: "^10.5.6"
  vite: "^8.2.0"
  "@vercel/speed-insights": "^2.0.0"
